select
    organization_id,
    tenant_name,
    tenant_domain,
    application_id,
    upper(module_key) as module_key,
    record_id,
    resolved_record_id,
    resolved_owner_id,
    resolved_team_id,
    resolved_territory_id,
    resolved_stage_value,
    schema_version,
    effective_schema_hash,
    cdc_timestamp,
    activity_date,
    operation_type,
    account_id,
    lead_id,
    activity_type,
    duration_seconds,
    outcome,
    try_parse_json(extras_json) as extras_json,
    pipeline_run_id,
    src_filename,
    loaded_at
from {{ source('wayplorer_landing', 'SILVER_ACTIVITY_RESOLVED_RAW') }}
