select
    organization_id,
    tenant_name,
    tenant_domain,
    tenant_company_size,
    application_id,
    upper(module_key) as module_key,
    record_id,
    resolved_record_id,
    resolved_owner_id,
    resolved_team_id,
    resolved_territory_id,
    resolved_stage_value,
    schema_version,
    effective_schema_hash,
    cdc_timestamp,
    operation_type,
    record_name,
    employee_band,
    annual_revenue_usd,
    health_score,
    lead_source,
    lead_score_hint,
    amount_usd,
    forecast_category,
    try_parse_json(extras_json) as extras_json,
    pipeline_run_id,
    src_filename,
    loaded_at
from {{ source('wayplorer_landing', 'SILVER_RECORDS_RESOLVED_RAW') }}
